version: '3'

services:
  app:
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - 8080:8080
    environment:
      spring.data.mongodb.host: db-mongo
    depends_on:
      - db-mongo
  db-mongo:
    image: mongo
    ports:
      - 27017:27017